version: "3.5"

#
# This docker compose needs .env file.
# Copy .env.example to .env and modify.
#

networks:
  default:
    attachable: true
    name: "${NEKO_ROOMS_TRAEFIK_NETWORK}"

services:
  traefik:
    image: "traefik:2.4"
    restart: "unless-stopped"
    environment:
      - "TZ"
    ports:
      - target: 80
        published: 80
        protocol: "tcp"
        mode: "host"
      - target: 443
        published: 443
        protocol: "tcp"
        mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./usersfile:/usersfile:ro"
      - "./acme.json:/acme.json"
      - "./config:/config"

  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    env_file:
      - ".env"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/neko-rooms/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.neko-rooms.rule=Host(`${NEKO_ROOMS_TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.neko-rooms.tls=true"
      - "traefik.http.routers.neko-rooms.tls.certresolver=${NEKO_ROOMS_TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.neko-rooms.middlewares=basicauth@file"